### ISSUE TITLE
Java - Clase completa

### ISSUE THREAD

**Issue by mchalin** [CodeSystem2022/UTN_BsAs_Tercer_Semestre#85]
8.1 Introducción a JavaBeans -> Creación del JavaBeans
8.2 Pruebas del JavaBeans
8.3 Comenzamos Con Excepciones -> Parte 1, 2 , 3 y 4
8.4 Creamos nuestra propia excepción -> Parte 1, 2 y 3
8.5 Comenzamos a hacer pruebas con RuntimeException (unchecked)
8.6 Agregamos el finally y catch

**Comment by DarioVega** [comment]
Finalizada
